spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csv2sql?serverTimezone=Asia/Seoul
    username: root
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
